resolver: lts-18.28
allow-newer: true

packages:
- core/lens
- core/optics
- core/rpc
- core/schema
- graphql
- instrumentation/prometheus
- instrumentation/tracing
- servant/server

extra-deps:
- http2-2.0.6
- warp-3.3.14
- http2-client-0.10.0.0
- warp-grpc-0.4.0.1
- graphql-1.0.3.0
- stm-hamt-1.2.0.7
- stm-containers-1.2
- tracing-0.0.7.2
- tracing-control-0.0.7.3
